<?php

/**
 * @file
 * Contains profile_module.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\drupal_set_message;
use Drupal\Core\Entity\t;
use Drupal\Core\Entity\EntityInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;

function profile_module_user_insert(EntityInterface $entity){
  drupal_set_message('Your account is registered our admin team will look & activate your account');	
}

function profile_module_user_login($account){
  $roles = $account->getRoles();
  if(in_array('administrator', $roles)) {
    $response = new RedirectResponse('/new-drupal/web/inactive-users');
    $response->send();
  }	else{
    $response = new RedirectResponse('/new-drupal/web/add-profile');
    $response->send();
  }
}
function profile_module_theme() {
  return [
    'view_profile' => [
      'render element' => 'children',
      'variables' => array(
        'content' => NULL,
      ),
    ],
  ];
}